Repository nyeoni/eyeRsee, pull requests merged in 2023-03, with the labels that each got.

#4 [Feature] Update github action build.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/build.yml
Labels: enhancement

#9 [Feature] irc structure
  .gitignore
  .vscode/settings.json
  Makefile
  include/Channel.hpp
  include/ChannelController.hpp
  include/Client.hpp
  include/ClientController.hpp
  include/EventHandler.hpp
  include/Response.hpp
  include/Server.hpp
  include/Socket.hpp
  src/EventHandler.cpp
  src/Response.cpp
  src/Server.cpp
  src/Socket.cpp
  src/controller/ChannelController.cpp
  src/controller/ClientController.cpp
  src/entity/Channel.cpp
  src/entity/Client.cpp
  src/main.cpp
Labels: enhancement

#10 [Feature] makefile 수정
  Makefile
  include/ChannelController.hpp
  include/controller/ChannelController.hpp
  include/controller/ClientController.hpp
  include/controller/EventHandler.hpp
  include/core/Response.hpp
  include/core/Server.hpp
  include/core/Socket.hpp
  include/entity/Channel.hpp
  include/entity/Client.hpp
  src/Response.cpp
  src/controller/ChannelController.cpp
  src/controller/ClientController.cpp
  src/core/EventHandler.cpp
  src/core/Response.cpp
  src/core/Server.cpp
  src/core/Socket.cpp
  src/main/main.cpp
Labels: enhancement

#11 [feature] EventHandler 헤더파일 이동
  include/core/EventHandler.hpp
Labels: enhancement

#12 [Feature] cmake GitHub config
  .github/workflows/build.yml
  .gitignore
  .idea/.gitignore
  .idea/ft_irc.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  CMakeLists.txt
  include/core/Server.hpp
  src/core/EventHandler.cpp
Labels: enhancement

#14 [Feature] Command parsing
  .idea/codeStyles/codeStyleConfig.xml
  CMakeLists.txt
  Makefile
  include/controller/ChannelController.hpp
  include/controller/Executer.hpp
  include/core/EventHandler.hpp
  include/core/Parser.hpp
  include/core/Response.hpp
  include/core/Server.hpp
  include/core/Socket.hpp
  include/core/Type.hpp
  include/core/Udata.hpp
  include/entity/Channel.hpp
  include/entity/Client.hpp
  src/controller/Executer.cpp
  src/core/EventHandler.cpp
  src/core/Parser.cpp
  src/core/Response.cpp
  src/core/Server.cpp
  src/core/Socket.cpp
  src/core/Udata.cpp
  test/CMakeLists.txt
  test/main.cpp
  test/parsing_test.cpp
  test/test.txt
Labels: enhancement

#15 :sparkles: feat: Add mode method of Executor
  include/controller/Executor.hpp
  include/core/Type.hpp
  include/entity/Channel.hpp
  src/controller/Executor.cpp
  src/entity/Channel.cpp
Labels: enhancement

#16 [Feature] Add part method of Executor
  include/controller/ChannelController.hpp
  include/controller/ClientController.hpp
  include/controller/Executor.hpp
  include/entity/Channel.hpp
  include/entity/Client.hpp
  src/controller/ChannelController.cpp
  src/controller/ClientController.cpp
  src/controller/Executor.cpp
  src/entity/Channel.cpp
  src/entity/Client.cpp
Labels: enhancement

#17 [Feature] Add topic method of Executor
  include/controller/ChannelController.hpp
  include/controller/ClientController.hpp
  include/controller/Executor.hpp
  include/entity/Channel.hpp
  src/controller/ChannelController.cpp
  src/controller/ClientController.cpp
  src/controller/Executor.cpp
  src/entity/Channel.cpp
Labels: enhancement

#18 [Feature] Add invite method of Executor
  include/controller/ChannelController.hpp
  include/controller/ClientController.hpp
  include/controller/Executor.hpp
  include/entity/Client.hpp
  src/controller/ChannelController.cpp
  src/controller/ClientController.cpp
  src/controller/Executor.cpp
  src/entity/Client.cpp
Labels: enhancement

#20 [Feature] Add kick method of Executor
  .vscode/settings.json
  include/controller/Executor.hpp
  src/controller/ClientController.cpp
  src/controller/Executor.cpp
Labels: enhancement

#21 [Feature] Add Executor.connect, Sever.handleConnect
  Makefile
  include/controller/ClientController.hpp
  include/controller/Executor.hpp
  include/core/Parser.hpp
  include/core/Socket.hpp
  include/core/Type.hpp
  include/core/Udata.hpp
  include/entity/Client.hpp
  src/controller/ClientController.cpp
  src/controller/Executor.cpp
  src/core/Server.cpp
  src/core/Socket.cpp
  src/core/Udata.cpp
  src/core/utility.cpp
  src/entity/Client.cpp
Labels: enhancement

#22 [Feature] executor
  .vscode/settings.json
  CMakeLists.txt
  Makefile
  include/controller/ChannelController.hpp
  include/controller/ClientController.hpp
  include/controller/Executer.hpp
  include/controller/Executor.hpp
  include/core/Parser.hpp
  include/core/Server.hpp
  include/core/Socket.hpp
  include/core/Type.hpp
  include/core/Udata.hpp
  include/entity/Channel.hpp
  include/entity/Client.hpp
  src/controller/ChannelController.cpp
  src/controller/ClientController.cpp
  src/controller/Executer.cpp
  src/controller/Executor.cpp
  src/core/Server.cpp
  src/core/Socket.cpp
  src/core/Udata.cpp
  src/core/utility.cpp
  src/entity/Channel.cpp
  src/entity/Client.cpp
Labels: enhancement

#25 [Feature] Command parsing
  CMakeLists.txt
  Makefile
  include/core/Parser.hpp
  include/core/Type.hpp
  include/core/Udata.hpp
  src/core/EventHandler.cpp
  src/core/Parser.cpp
  src/core/Server.cpp
  src/core/Udata.cpp
  src/core/utility.cpp
  test/parsing_test.cpp
Labels: enhancement

#24 [Feature] Executor::privmsg 함수 구현
  include/controller/ChannelController.hpp
  include/controller/ClientController.hpp
  include/controller/Executor.hpp
  include/core/Udata.hpp
  include/entity/Client.hpp
  src/controller/ChannelController.cpp
  src/controller/ClientController.cpp
  src/controller/Executor.cpp
  src/core/Server.cpp
Labels: enhancement

#26 [Feature] Mode parsing & Update validate function
  include/core/Parser.hpp
  include/core/Udata.hpp
  src/core/Parser.cpp
Labels: enhancement

#32 [BugFix] validNick error
  src/core/Parser.cpp
Labels: bug

#34 [Feature] Update handler dir
  CMakeLists.txt
  Makefile
  include/core/Server.hpp
  include/handler/ErrorHandler.hpp
  include/handler/EventHandler.hpp
  src/handler/ErrorHandler.cpp
  src/handler/EventHandler.cpp
Labels: enhancement

#33 [Feature] Update prompt art
  include/core/Server.hpp
  src/core/Server.cpp
Labels: enhancement

#31 [Feature] executor 함수 broadcast 추가
  include/controller/ChannelController.hpp
  include/controller/ClientController.hpp
  include/controller/Executor.hpp
  include/core/Type.hpp
  src/controller/ChannelController.cpp
  src/controller/ClientController.cpp
  src/controller/Executor.cpp
  src/core/Server.cpp
  src/entity/Channel.cpp
  src/handler/EventHandler.cpp
Labels: enhancement

#36 [Feature] Update errorhandler
  CMakeLists.txt
  include/core/Udata.hpp
  include/handler/ErrorHandler.hpp
  src/core/Server.cpp
  src/handler/EventHandler.cpp
Labels: enhancement

#37 [Refactor] Executor connect, execute 함수 추가
  include/controller/Executor.hpp
  include/core/Udata.hpp
  src/controller/Executor.cpp
  src/core/Server.cpp
  src/core/Udata.cpp
Labels: enhancement

#38 [Feature] Refactor Parsing & Fix execute join error
  .vscode/settings.json
  include/controller/ChannelController.hpp
  include/controller/Executor.hpp
  include/core/Server.hpp
  include/core/Socket.hpp
  src/controller/ChannelController.cpp
  src/controller/Executor.cpp
  src/core/Server.cpp
  src/core/Socket.cpp
  test/parsing_test.cpp
Labels: bug, enhancement

#39 [Feature] Add EventHandler::garbageCollector
  include/controller/Executor.hpp
  include/core/Server.hpp
  include/core/Socket.hpp
  include/core/Type.hpp
  include/core/Udata.hpp
  include/handler/EventHandler.hpp
  src/controller/Executor.cpp
  src/core/Server.cpp
  src/core/Udata.cpp
  src/entity/Client.cpp
  src/handler/EventHandler.cpp
Labels: enhancement

#44 [Fix] Hotfix/executor
  Makefile
  include/core/Type.hpp
  include/core/Udata.hpp
  include/handler/EventHandler.hpp
  src/controller/ChannelController.cpp
  src/controller/ClientController.cpp
  src/controller/Executor.cpp
  src/core/Server.cpp
  src/core/Socket.cpp
  src/core/Udata.cpp
  src/entity/Client.cpp
  src/handler/EventHandler.cpp
Labels: bug, enhancement

#46 [Feature] Errorhandler & ResponseHandler
  CMakeLists.txt
  include/core/Parser.hpp
  include/core/Server.hpp
  include/entity/Client.hpp
  include/handler/ErrorHandler.hpp
  include/handler/ResponseHandler.hpp
  src/controller/Executor.cpp
  src/core/Parser.cpp
  src/core/Server.cpp
  src/entity/Client.cpp
  src/handler/ErrorHandler.cpp
  test/parsing_test.cpp
Labels: enhancement

#47 Feature/errorhandler
  CMakeLists.txt
  include/handler/ErrorHandler.hpp
  include/handler/ResponseHandler.hpp
  src/controller/Executor.cpp
  src/core/Server.cpp
Labels: enhancement

#49 [Feature] write event handle
  include/controller/Executor.hpp
  include/core/Server.hpp
  include/core/Socket.hpp
  include/core/Type.hpp
  include/core/Udata.hpp
  include/core/utility.hpp
  include/handler/EventHandler.hpp
  src/controller/Executor.cpp
  src/core/Server.cpp
  src/core/Socket.cpp
  src/core/utility.cpp
  src/handler/EventHandler.cpp
Labels: enhancement

#51 [Feature] Parsing error handling
  CMakeLists.txt
  include/core/Parser.hpp
  include/handler/ErrorHandler.hpp
  src/core/Parser.cpp
  src/core/Server.cpp
  src/handler/ErrorHandler.cpp
Labels: enhancement

#52 [Refactor] executor
  include/controller/ChannelController.hpp
  include/controller/ClientController.hpp
  include/controller/Executor.hpp
  include/core/Socket.hpp
  include/entity/Channel.hpp
  include/entity/Client.hpp
  include/handler/ResponseHandler.hpp
  src/controller/ChannelController.cpp
  src/controller/ClientController.cpp
  src/controller/Executor.cpp
  src/core/Server.cpp
  src/core/Socket.cpp
  src/entity/Channel.cpp
  src/entity/Client.cpp
Labels: enhancement

#53 [Feature] notice ping
  CMakeLists.txt
  include/controller/Executor.hpp
  include/handler/ErrorHandler.hpp
  include/handler/ResponseHandler.hpp
  src/controller/Executor.cpp
  src/core/Parser.cpp
  src/handler/ErrorHandler.cpp
  src/handler/EventHandler.cpp
  src/handler/ResponseHandler.cpp
Labels: enhancement

#54 [Refactor] Refactor executer & register events
  include/controller/Executor.hpp
  include/core/Server.hpp
  include/core/Type.hpp
  include/handler/EventHandler.hpp
  src/controller/Executor.cpp
  src/core/Server.cpp
  src/handler/EventHandler.cpp
Labels: bug, enhancement

#55 [Refactor] createChannel
  include/controller/ChannelController.hpp
  include/entity/Channel.hpp
  src/controller/ChannelController.cpp
  src/entity/Channel.cpp
Labels: enhancement

#56 [FIX] add EventHandler::udata_list
  include/controller/Executor.hpp
  include/core/Server.hpp
  include/core/Socket.hpp
  include/core/Type.hpp
  include/core/Udata.hpp
  include/handler/EventHandler.hpp
  src/controller/Executor.cpp
  src/core/Parser.cpp
  src/core/Server.cpp
  src/core/Socket.cpp
  src/core/Udata.cpp
  src/handler/EventHandler.cpp
Labels: bug, enhancement

#61 [Feature] Create refactor issue template
  .github/ISSUE_TEMPLATE/-refactor-.md
Labels: documentation

#66 [Refactor] 1.0.1
  CMakeLists.txt
  Makefile
  include/controller/Executor.hpp
  include/core/Command.hpp
  include/core/Parser.hpp
  include/core/Server.hpp
  include/core/Socket.hpp
  include/core/utility.hpp
  include/entity/Client.hpp
  include/handler/ErrorHandler.hpp
  include/handler/EventHandler.hpp
  include/handler/ResponseHandler.hpp
  report.xml
  src/controller/Executor.cpp
  src/core/Command.cpp
  src/core/Parser.cpp
  src/core/Server.cpp
  src/core/Socket.cpp
  src/core/Udata.cpp
  src/core/utility.cpp
  src/entity/Client.cpp
  src/handler/ErrorHandler.cpp
  src/handler/EventHandler.cpp
  src/handler/ResponseHandler.cpp
  test/parsing_test.cpp
Labels: bug, enhancement

#68 [BugFix] msg parse error
  CMakeLists.txt
  src/core/Parser.cpp
  src/handler/ResponseHandler.cpp
Labels: bug, enhancement

#69 [BugFix] Update wrong pass err_code and handling msg
  include/handler/ErrorHandler.hpp
  src/controller/Executor.cpp
  src/handler/ErrorHandler.cpp
Labels: bug, enhancement

#70 [BugFix] Fix user register error
  src/core/Server.cpp
  src/handler/ErrorHandler.cpp
Labels: bug

#72 [BugFix] notice handleResponse syntax error
  src/core/Parser.cpp
  src/handler/ResponseHandler.cpp
Labels: bug

#73 [BugFix] join response
  include/controller/ChannelController.hpp
  include/controller/ClientController.hpp
  include/handler/ResponseHandler.hpp
  src/controller/ChannelController.cpp
  src/controller/ClientController.cpp
  src/controller/Executor.cpp
  src/core/Server.cpp
  src/handler/ResponseHandler.cpp
Labels: bug

#74 [BugFix] kick (kicker) response error
  src/controller/Executor.cpp
  src/core/Parser.cpp
Labels: bug

#76 [BugFix] UnHandledModeException in Parser.cpp
  include/core/Parser.hpp
  src/core/Parser.cpp
Labels: bug, enhancement

#78 [BugFix] MODE response
  .vscode/settings.json
  src/controller/ChannelController.cpp
  src/controller/Executor.cpp
  src/core/Parser.cpp
  src/entity/Channel.cpp
  src/handler/ResponseHandler.cpp
Labels: bug

#79 [BugFix] Fix topic parse error
  include/controller/BotController.hpp
  src/core/Parser.cpp
Labels: bug

#80 [BugFix] topic 동작 수정
  src/controller/ChannelController.cpp
  src/controller/Executor.cpp
Labels: bug

#77 [BugFix] quit, add updateClient status
  include/controller/ClientController.hpp
  include/controller/Executor.hpp
  include/core/Server.hpp
  include/core/Socket.hpp
  include/core/Type.hpp
  src/controller/ClientController.cpp
  src/controller/Executor.cpp
  src/core/Server.cpp
  src/core/Socket.cpp
  src/entity/Client.cpp
Labels: bug, enhancement

#81 [Refactor] 1.0.2
  include/controller/Executor.hpp
  include/core/Parser.hpp
  include/core/Server.hpp
  include/handler/EventHandler.hpp
  src/controller/Executor.cpp
  src/core/Parser.cpp
  src/core/Server.cpp
  src/handler/EventHandler.cpp
Labels: enhancement

#84 [Feature] EyeRsee bot
  CMakeLists.txt
  Makefile
  include/controller/BotController.hpp
  include/controller/Executor.hpp
  include/core/Command.hpp
  include/core/Parser.hpp
  include/core/Type.hpp
  include/core/utility.hpp
  include/handler/ResponseHandler.hpp
  report.xml
  src/controller/BotController.cpp
  src/controller/Executor.cpp
  src/core/Parser.cpp
  src/core/utility.cpp
  src/handler/ResponseHandler.cpp
  test/parsing_test.cpp
Labels: enhancement

#85 [Refactor] Parser & bot command
  include/controller/BotController.hpp
  include/core/Command.hpp
  include/core/Parser.hpp
  src/controller/BotController.cpp
  src/controller/Executor.cpp
  src/core/Parser.cpp
  src/core/Server.cpp
Labels: bug, enhancement

#83 [BugFix] INVITE, MODE 관련 에러 처리
  include/controller/ChannelController.hpp
  include/entity/Channel.hpp
  include/entity/Client.hpp
  include/handler/ResponseHandler.hpp
  src/controller/ChannelController.cpp
  src/controller/ClientController.cpp
  src/controller/Executor.cpp
  src/entity/Channel.cpp
  src/entity/Client.cpp
  src/handler/ErrorHandler.cpp
  src/handler/ResponseHandler.cpp
Labels: bug, enhancement

#86 [Hotfix] make error
  .github/workflows/build.yml
  include/controller/BotController.hpp
  include/controller/ChannelController.hpp
  include/controller/ClientController.hpp
  include/controller/Executor.hpp
  include/core/Command.hpp
  include/core/Parser.hpp
  include/core/Server.hpp
  include/core/Socket.hpp
  include/core/Type.hpp
  include/entity/Channel.hpp
  include/entity/Client.hpp
  include/handler/ErrorHandler.hpp
  include/handler/EventHandler.hpp
  include/handler/ResponseHandler.hpp
  src/controller/BotController.cpp
  src/controller/ChannelController.cpp
  src/controller/ClientController.cpp
  src/controller/Executor.cpp
  src/core/Command.cpp
  src/core/Parser.cpp
  src/core/Server.cpp
  src/core/Socket.cpp
  src/entity/Client.cpp
  src/handler/ErrorHandler.cpp
  src/handler/EventHandler.cpp
  src/handler/ResponseHandler.cpp
  src/main/main.cpp
Labels: bug, enhancement
